# @Author: Daniel Gangl
# @Date:   2021-12-31 14:26:43
# @Last Modified by:   Daniel Gangl
# @Last Modified time: 2021-12-31 15:27:54
name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag killer007/cybroscgiserver:$(date +%s)
